language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sameckmeier/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sameckmeier/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  # The S3 bucket and dir in bucket that stores all config/hosting files
  bucket_name: "elasticbeanstalk-us-east-1-059673065443"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
